### ISSUE TITLE
Use Open Community Data

### ISSUE THREAD

**Issue by EmiiKhaos** [tightenco/symposium#161]
I don't know how conferences are populated into Symposium, but it would be neat to use Open Community Data: https://github.com/afilina/dev-community-data

**Comment by mattstauffer** [comment]
Right now it's manual and then also pulls in Joind.In. It would be very nice to pull in as many sources of data as possible.

**Comment by michaelrtm** [comment]
Hey @mattstauffer, would the starting point for this be looking at creating something like an `ImportConference` contract that had maybe `import`, `create` and `update` methods? I think I'd then rewrite the `JoindIn/ConferenceImporter` to implement that contract, instead of having method names like `updateConferenceFromJoindInEvent`, then start on actually implementing this?

Checking if this would be the correct starting point, as I've never implemented something like this before.

**Comment by mattstauffer** [comment]
@michaelrtm Sure, although I don't know if I trust a contract, because the parameters of the sort of data we'd be getting in would be different for each.

Each importer is responsible for taking data from an external service and transforming it and inserting or updating it into our database. 

It may make sense to have a single method like `sync` that each offers, and if we need something else (e.g. forcing an individual conference ID to update from its source) we could do that--but only if there's a practical need for it.

Beware of abstractions and interfaces for the sake of abstraction and interface; rather, create them when you see the need for them.
