### ISSUE TITLE
[Proposal] Ability to search public speaker profiles

### ISSUE THREAD

**Issue by greydnls** [tightenco/symposium#166]
As a conference/UG organizer it would probably be helpful to filter speaker profiles by location. 

I think this would require adding in some additional fields to speaker's bio for airport or locale, but that could be done easily enough.

**Comment by mattstauffer** [comment]
:+1:

**Comment by Xethron** [comment]
I think this should be on the users profile instead of their bio... And perhaps even a "traveling" option, that allows you to set a from/to date in a different location that you will be open for presenting...

So you have a "Default", and a travel "Open for speaking". That way, when you search, you'll also find speakers with travel times close to that location in the future. (Phase 2)

**Comment by mattstauffer** [comment]
source for some airport data for when we add this:

https://github.com/opencfp/opencfp/blob/2f747fc219b73f9b0a11308083d2a356056752a4/migrations/20151214140200_airports.php

**Comment by mattstauffer** [comment]
(closed because we added it)
