### ISSUE TITLE
Add GitHub login

### ISSUE THREAD

**Issue by adamwathan** [tightenco/symposium#56]
UPDATE: See bottom of the thread for our final decision that now needs to be implemented: https://github.com/tightenco/symposium/issues/56#issuecomment-101016944

----------------------------

The Gravatar PR got me thinking. If we are targeting tech conferences (which I think we should, it's a huge market on it's own but still focused enough that we can really provide an optimized experience), maybe GitHub login would be a good idea?

Gravatar sort of annoys me because the only way you have one is if you created a free Wordpress.com blog or manually created a Gravatar account. With GitHub login, we turn the sign up process into a single click (I seriously love logging in with GitHub for tech sites), and we have a way higher chance of getting a good default avatar. Should still allow people to override it with a new photo for their bios, but still. Could even see down the road how it might be cool to like "Export your Symposium data to a GitHub repo" through the GitHub API.

If you think it's a good idea, I would suggest making it the primary sign up option, maybe even only sign up option, and providing a link for users with legacy accounts to still login with email/password and then get prompted to link their GitHub account.

What do you think?

**Comment by adamwathan** [comment]
For @mattstauffer

**Comment by mattstauffer** [comment]
I think I'd rather it be secondary. Sort of like Packagist, which is *clearly* tied to Github, still has its own login/etc. but just has a "Login with Github" button.

This is because I want to keep it open and usable for non-tech. It's sort of like what we did with Karani: make an app that's broadly usable but start with a smaller, known target market.

So: I agree that it'd be helpful, but I want it to be *fully* functional without it. :)

**Comment by mattstauffer** [comment]
(Thoughts @adamwathan ?)

**Comment by besologic** [comment]
If you're focusing on tech initially though, why wouldn't you focus on nailing that experience before widening it? You can always roll out a full-login system at that point.

**Comment by mattstauffer** [comment]
Because we already have a fully functional login. There's no reason to get rid of it if we know we're going to want it later. And I don't want it to be only usable to tech people now and then usable for others later when there's nothing we could save time/effort on by ignoring non-tech people. If we were having this question up front, we could say "github login is cheaper than github plus custom", but since we would have to support current users, that's not an option.

**Comment by adamwathan** [comment]
@mattstauffer: Yeah I think that works.

The only thing I would say is that I would hesitate to worry _too_ much about keeping things super generalized because I think it can hurt your ability to deliver a really useful product that solves clear pain points we understand really well as tech speakers. The tech conference scene is _massive_, especially when you factor in non-PHP tech conferences, so I think there's a big opportunity to build something great there.

I defer to the great Ryan Singer :smile: 

> When the job isn’t well-defined, the team doesn’t know what to include and what to omit. They design based on logical speculations, not real situations. Instead of targeting a problem like a sniper, they cast a net and hope to catch the value somewhere within its expanse. Casting a net means building more functionality in more places, so the project grows in scope and complexity.

**Comment by mattstauffer** [comment]
LOL, how did I know Ryan Singer would get quoted?

I agree. But to me, that doesn't mean "putting things int he way of non-tech people using it". That just means "prioritizing making it awesome for tech people."

We design toward techies, but don't put unnecessary hurdles in the way of non-techies.

**Comment by mattstauffer** [comment]
Remember that law that says "any conversation on the internet will eventually have Hitler referenced" or something like that? Was it Godwin's law? We need Wathan's law. Any Tighten Co. conversation about product design, if it goes long enough, will have Ryan Singer quoted. :)

(And I'm not mad about that, especially not that particular quote)

**Comment by adamwathan** [comment]
You don't want to throw away ideas that reduce barriers _for_ tech speakers though just because it might increase barriers for the 1%. That's like when no one gets to eat Mexican food in San Diego just because friggin' Adam Wathan is there.

Anyways, not really talking about the GitHub login idea at this point, really just trying to get on the same page as far as project goals. I don't think designing for the lowest common denominator should be rule number one. It makes sense to me to always consider "how much does this improve the product for our core market vs. how much does it hurt it for the rest", but I think it's a bad idea to throw out any idea that hurts the 1% without considering if it might improve the experience by 100% for the rest of the user base, s'all.

Re: the GitHub idea, I think supporting both is good. I do think designing the sign up/login process in such a way that it [affords](http://www.quora.com/What-are-examples-of-affordances) logging in with GitHub more strongly than it does email makes sense though, because if 99/100 users have a GitHub account, we can automatically import their profile picture with a much higher hit rate than Gravatar.

It also opens the doors for other feature ideas, like checking what languages your public repositories use and prominently featuring Open CFPs that are based around technologies you use to make it easier to see conferences you might actually want to submit to, without ever having to fill out any preferences or do any manual filtering.

I think it opens more doors for us when it comes to [giving our users super powers](http://www.darkcoding.net/future-of-web-apps/kathy-sierra-give-your-users-super-powers/), which I'm realizing more and more is the key to building a product people love to use.

**Comment by mattstauffer** [comment]
I think we're saying the same thing by this point. Target tech users. Don't unnecessarily block non tech users. Feel free to give tech users superpowers even if in a way that doesn't give the same superpowers to non tech users . 👍
Sent from Outlook




On Mon, May 11, 2015 at 10:55 AM -0700, "Adam Wathan" <notifications@github.com> wrote:












You don't want to throw away ideas that reduce barriers for tech speakers though just because it might increase barriers for the 1%. That's like when no one gets to eat Mexican food in San Diego just because friggin' Adam Wathan is there.



Anyways, not really talking about the GitHub login idea at this point, really just trying to get on the same page as far as project goals. I don't think designing for the lowest common denominator should be rule number one. It makes sense to me to always consider "how much does this improve the product for our core market vs. how much does it hurt it for the rest", but I think it's a bad idea to throw out any idea that hurts the 1% without considering if it might improve the experience by 100% for the rest of the user base, s'all.



Re: the GitHub idea, I think supporting both is good. I do think designing the sign up/login process in such a way that it affords logging in with GitHub more strongly than it does email makes sense though, because if 99/100 users have a GitHub account, we can automatically import their profile picture with a much higher hit rate than Gravatar.



It also opens the doors for other feature ideas, like checking what languages your public repositories use and prominently featuring Open CFPs that are based around technologies you use to make it easier to see conferences you might actually want to submit to, without ever having to fill out any preferences or do any manual filtering.



I think it opens more doors for us when it comes to giving our users super powers, which I'm realizing more and more is the key to building a product people love to use.

**Comment by dhicking** [comment]
Actually, I don't think you two are on the same page at all.

Benson reminded me that this is still in the early stages of the development, which means we need to be hyper focused on three questions:

1) What problem are we trying to solve?
2) What solution do we have to this problem that's compelling?
3) What group of people are we designing this solution for?

By the way, the answer to 3 (at least right now) **can't** be 'everybody who presents at a conference'.  We aren't representative of the entire population of people who present at a conference, so unless we plan on doing a ton of research, (to quote Benson) "we have to solve the problem that we understand".

If we're focusing on people who present at tech conferences, then we need to make it amazing for that audience.  **Amazing**.

**Comment by besologic** [comment]
(BTW - this is fantastic discussion. We need to sharpen our product decision chops.)

**Comment by mattstauffer** [comment]
Everything you wrote in your thing, @dhicking, is still in line with what I'm saying.

We're not solving for everyone who presents at a conference. But we're also not solving for tech speakers. There will be a large portion of tech speakers who don't care enough to use this. We have a very small market if we only have tech speakers who care enough to use this. So, instead, we have "speakers who speak often enough to need a tool like this" as our vague eventual top target and "tech speakers who speak often enough to need a tool like this" as our immediate target.

Your questions.
1. Keeping track of your talk abstracts in their various stages--original ideas, edits/history, submissions, acceptance, and possibly automatically sending it in. This of course applies to other aspects of the talk submission process (bios, pics), but they're less primary.
2. An app that does that? lol, i dunno 
3. See my paragraph above.

So far I haven't seen a single thing that says "allowing non-github login will have any negative impact on our ability to make it amazing."

Let's take my statement from another angle: Talk about it from a purely tech person standpoint.

Not everyone likes Github logins. Getting rid of non-Github logins is a bad idea. I may or may not be able to word it in a way that lines up with this line of thinking. But it's not a good idea. So, even in the tech-speaker-only world, Github login only is not acceptable.

So, that leaves us with using Github login as a strong option that conveys significant benefits, but allowing the app to remain functional with non Github login. Which is what Adam suggested above, and what I want, and so like I said, we're on the same page. :)

**Comment by adamwathan** [comment]
@mattstauffer @dhicking @besologic 

I think the most important thing is to understand that every decision a user has to make introduces friction into the experience.

So while allowing both options in this particular place isn't going to be a big deal on it's own, the sum of allowing a lot of choices like that _will_ eventually be a big deal.

I totally am on board with keeping standard email login. Our stance on it though does affect little decisions.

If we want to encourage GitHub login for anyone that _has_ a GitHub account, the sign up page might look like this:

![image](https://cloud.githubusercontent.com/assets/4323180/7572391/cfe550ee-f7eb-11e4-93f5-89cd7e62c716.png)

If we want to give people the _option_ to sign in with GitHub, it might look like this:

![image](https://cloud.githubusercontent.com/assets/4323180/7572563/09c767f6-f7ed-11e4-93fa-88584873a72c.png)

It isn't anything crazy but one option clearly makes a suggestion that the other one doesn't.

It would look different again if we wanted to encourage email login.

Maybe we want to appeal to everyone, but let tech speakers know that logging in with GitHub is gonna make it even more awesome to them. Then maybe it looks like this:

![image](https://cloud.githubusercontent.com/assets/4323180/7572670/ecfaee3a-f7ed-11e4-91cf-eb1f5d017258.png)

Just stuff to think about anyways.

**I'm just trying to do a good job here guys.**

**Comment by mattstauffer** [comment]
BALLELRRRRRRR

I like the first one, but I'm open to the second one. But I prefer the 1st.

On Mon, May 11, 2015 at 2:57 PM, Adam Wathan <notifications@github.com>
wrote:

> @mattstauffer <https://github.com/mattstauffer> @dhicking
> <https://github.com/dhicking> @besologic <https://github.com/besologic>
>
> I think the most important thing is to understand that every decision a
> user has to make introduces friction into the experience.
>
> So while allowing both options in this particular place isn't going to be
> a big deal on it's own, the sum of allowing a lot of choices like that
> *will* eventually be a big deal.
>
> I totally am on board with keeping standard email login. Our stance on it
> though does affect little decisions.
>
> If we want to encourage GitHub login for anyone that *has* a GitHub
> account, the sign up page might look like this:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/4323180/7572391/cfe550ee-f7eb-11e4-93f5-89cd7e62c716.png>
>
> If we want to give people the *option* to sign in with GitHub, it might
> look like this:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/4323180/7572563/09c767f6-f7ed-11e4-93fa-88584873a72c.png>
>
> It isn't anything crazy but one option clearly makes a suggestion that the
> other one doesn't.
>
> It would look different again if we wanted to encourage email login.
>
> Maybe we want to appeal to everyone, but let tech speakers know that
> logging in with GitHub is gonna make it even more awesome to them. Then
> maybe it looks like this:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/4323180/7572670/ecfaee3a-f7ed-11e4-91cf-eb1f5d017258.png>
>
> Just stuff to think about anyways.
>
> *I'm just trying to do a good job here guys.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tightenco/symposium/issues/56#issuecomment-101016944>.
>



-- 

*Matt Stauffer*
*Partner + Technical Director*
Tighten Co.
352-682-2765

**Comment by josecanhelp** [comment]
Solved with #211
